name: Build and Deploy Hugo Site

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: 'latest'
                extended: true

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '16'

          - name: Install dependencies
            run: |
                npm install

          - name: Build site
            run: hugo --minify

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public